#ifndef CONFIG_HPP                                                                           
#define CONFIG_HPP                                                                           
                                                                                                                               
#include "stdio.h"                                                                                                             
#include <vector>                                                                                                              
#include <fstream>                                                                                                                                                                                                                                                                                                      
#include <iostream>                                                                                                                                                                                                                                                                                                     
#include <string>                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                  
class Config                                                                                                                                                                                                                                                                                                                                                                                                      
{                                                                                                                                                                                                                                                                                                                                                                                                                 
    public:                                                                                                                                                                                                                                                                                                                                                                                                       
        void readText(std::string txt,std::string arrays[],std::string targets[]);                                                                                                                                                                                                                                                                                                                                                      
        int arr = 0;                                                                                                                                                                                                                                                                                                                                                                                              
        int header = 1;                                                                                                                                                                                                                                                                                                                                                                                           
        std::string target[8] = {"NumberofPlayers: ", "Name: ", "Type: ", "Birthplace: ", "Armor: ", "Health: ", "Mods: ", "Inv: "};                                                                                                                                                                                                                                                                              
        std::string invarr[6] = {"inv items: ", "Tabs inv: ", "Havoc inv: ", "Jerah inv: ", "Esme rin inv: ", "Magnus Inv: "};                                                                                                                                                                                                                                                                                    
        void configCharacters(int ii, std::string arrays);                                                                                                                                                                                                                                                                                                                                                                                                                  
        std::string* parseData(std::string array[], std::string target[]);                                                                                                                                                                                                                                                                                                                                                              
        int targetParse;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
        std::string array[100];                                                                                                                                                                                                                                                                                                                                                                                   
        std::string arrayInv[300];                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                  
};                                                                                                                                                                                                                                                                                                                                                                                                                
#endif                                                                                                                                                                                                                                                                                                                                                                                                            